contracts/control/unstructured/UInitializable.sol, contracts/mocks/MockUInitializable.sol, contracts/mocks/MockUJumpRateUtilizationCurveProvider.sol, contracts/mocks/MockULinearUtilizationCurveProvider.sol, contracts/mocks/MockUOwnable.sol, contracts/mocks/MockUReentrancyGuard.sol, contracts/package.json, package.json, test/unit/control/UInitializer.test.ts
Updates the `UInitializer` to support versions, keeping inline with the OZ feature set [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/utils/Initializable.sol).
- Fixes a bug where proxies could not call initializers on setup since constructor calls were explicitly blocked.
-Updates `root` to `v0.1.2` and adds OZ as a peer dependency.
=> [Update] Update UInitializer pattern

contracts/storage/UStorage.sol, hardhat.config.ts
Updates pragma in `UStorage.sol` to allow versions above `0.8.13`.
=> [Fix] Enable Solidity v0.8.14

contracts/control/unstructured/UInitializable.sol, test/unit/control/UInitializer.test.ts
Adds `event Initialized(uint256 version)`
=> [Partial Fix] L07 - Missing validation and events in init functions.

contracts/number/types/Fixed18.sol, test/unit/number/Fixed18.test.ts
This reduces the gas used by `from(int256, UFixed18)` from 22440 to 22313 with `viaIR`, saving 127 gas.
One other optimization considered was wrapping division by `BASE` in `unchecked`. However, that did not save any gas.
=> Unchecked math in number types

contracts/curve/types/JumpRateUtilizationCurve.sol, contracts/mocks/MockJumpRateUtilizationCurve.sol, contracts/mocks/MockToken6.sol, contracts/token/types/Token6.sol, package.json, test/unit/curve/JumpRateUtilizationCurve.test.ts, test/unit/token/Token6.test.ts
This change reverts v2 changes that make Root not backwards compatible. This allows us to include most of root v2 changes in the next comprehensive audit of Perennial v1.
Once we're ready for v2, we can revert this merge commit
=> Make Root backwards compatible

contracts/accumulator/types/Accumulator6.sol, contracts/accumulator/types/UAccumulator6.sol, test/unit/accumulator/Accumulator6.test.ts, test/unit/accumulator/UAccumulator6.test.ts
Currently the accumulator will always reverts with a divide-by-zero error when increment / decrementing with a zero value `total`.
This PR adds a check that allows the case of a zero-value `amount` being able to be used with a zero-value `total`.
This case is *correct* because no value is being distributed to no one, where as we would still want the case of some value being distributed to no one to revert since this can cause silent burning of assets.
=> Add accumulator zero check

contracts/control/interfaces/IPausable.sol, contracts/control/unstructured/UPausable.sol, contracts/mocks/MockUPausable.sol, test/unit/control/UPausable.test.ts
Mostly unchanged from the original, except I added a `__UPausable__initialize` function so that the pauser would be initialized.
=> Add UPausable

contracts/attribute/Kept/Kept.sol, contracts/attribute/Kept/Kept_Arbitrum.sol, contracts/attribute/Kept/Kept_Optimism.sol, contracts/mocks/MockKept_Arbitrum.sol, contracts/mocks/MockKept_Optimism.sol, test/unit/attribute/Kept.test.ts, test/unit/attribute/Kept_Arbitrum.test.ts, test/unit/attribute/Kept_Optimism.test.ts
Introduces new L2 versions of `Kept` which allows for inheriting contracts to instantiate a `dataSize` value to use to calculate the L1 portion of the keeper fees
Arb Docs: https://docs.arbitrum.io/devs-how-tos/how-to-estimate-gas#where-do-we-get-all-this-information-from
Opt Docs: https://community.optimism.io/docs/developers/build/transaction-fees/#the-l1-data-fee
=> Kept_{Optimism,Arbitrum}

contracts/attribute/Kept/Kept.sol, contracts/attribute/Kept/Kept_Arbitrum.sol, contracts/attribute/Kept/Kept_Optimism.sol, contracts/package.json
Followup from: https://github.com/equilibria-xyz/root/pull/74.
Adds minor cleanups + `virtual` on L2 implementation functions to enable proper mixin pattern.
=> [Cleanup] Kept

contracts/attribute/Kept/Kept.sol, contracts/attribute/Kept/Kept_Arbitrum.sol, contracts/attribute/Kept/Kept_Optimism.sol, contracts/attribute/interfaces/IKept.sol, contracts/mocks/MockKept.sol, contracts/mocks/MockKept_Arbitrum.sol, contracts/mocks/MockKept_Optimism.sol, test/unit/attribute/Kept.test.ts, test/unit/attribute/Kept_Arbitrum.test.ts, test/unit/attribute/Kept_Optimism.test.ts
Improves the accounting of `Kept`'s `keep` modifier by adding the following functionality:
- Splits `multiplier` / `buffer` into two sets: one for the base fee, and one for the calldata fee (optionally used in L2 implementations)
- Adds an `applicableValue` field to account for Ether passed in to pay for the function call.
=> Improve Kept

contracts/mocks/MockUFixed18.sol, contracts/mocks/MockUFixed6.sol, contracts/number/types/UFixed18.sol, contracts/number/types/UFixed6.sol, contracts/package.json, test/unit/number/UFixed18.test.ts, test/unit/number/UFixed6.test.ts
Adds two new `unsafe` functions to `UFixed` number types:
- `unsafeFrom`: defaults to `ZERO` instead of reverting with a negative input.
- `unsafeSub`: returns `ZERO` instead of underflowing when the result would be negative.
=> Add unsafeSub / unsafeFrom

contracts/attribute/Kept/Kept.sol, contracts/attribute/Kept/Kept_Arbitrum.sol, contracts/attribute/Kept/Kept_Optimism.sol, contracts/mocks/MockKept.sol, contracts/mocks/MockKept_Arbitrum.sol, contracts/mocks/MockKept_Optimism.sol, contracts/package.json
- Adds a `_handleKeeperFee` internal hook that can be used in place of the `keep` modifier if gas does not need to be measured.
- Moves `applicableData` from calldata -> memory to increase flexibility (at the expense of gas cost).
- Allows `_raiseKeeperFee` to raise less than is requested without revert.
=> Add Kept internal hook

contracts/access/ProxyOwner.sol, test/unit/access/ProxyOwner.test.ts
Adds two-step flows for all ownership transfers
Uses `Ownable2Step` to create process:
1. `owner -> .transferOwnership(newOwner)`
2. `newOwner -> .acceptOwnership()`
Overrides / Adds methods to create process:
1. `proxyOwner.owner -> proxyOwner.changeProxyAdmin(newProxyOwner)`
2. `newProxyOwner.owner -> newProxyOwner.acceptProxyAdmin(proxyOwner, newProxyOwner)`
=> Add ProxyOwner

contracts/package.json, contracts/verifier/VerifierBase.sol, contracts/verifier/interfaces/IVerifierBase.sol, contracts/verifier/types/Common.sol, contracts/verifier/types/GroupCancellation.sol, hardhat.config.ts, package.json, test/testutil/erc712.ts, test/unit/verifier/VerifierBase.ts
- Adds `signer` field to `Common` message type
- Adds support for `EIP1271` signatures w/ `Common` / `GroupCancellation` message types
Required to support `EIP1271` signature checking since we need to know the signer at time of check.
=> Add signer field to Common in Verifier

contracts/attribute/Factory.sol, contracts/mocks/MockFactory.sol, test/unit/attribute/Factory.test.ts
Planning to use this in collateral accounts to deploy _BeaconProxies_ for `Account`, with `Controller` as the beacon.
=> Extend factory to support create2

contracts/attribute/Kept/Kept_Arbitrum.sol, contracts/attribute/Kept/Kept_Optimism.sol, contracts/gas/GasOracle.sol, contracts/gas/GasOracle_Arbitrum.sol, contracts/gas/GasOracle_Optimism.sol, contracts/gas/interfaces/IGasOracle.sol, contracts/mocks/GasOracleRunner.sol, contracts/package.json, package.json, test/unit/gas/GasOracle.test.ts, test/unit/gas/GasOracle_Arbitrum.test.ts, test/unit/gas/GasOracle_Optimism.test.ts
Adds a generic external gas oracle contract.
This works similarly to `Kept` but instead offloads complexity to an external contract for cases where multiple concurrently incentivization flows need to be manage independently.
=> Add GasOracle

test/unit/verifier/VerifierBase.ts
Readded tests which were removed by #104 .  As with the old tests, the signature check is mocked and it's being signed by the caller rather than the sc.
=> Re-add sc verifier tests

contracts/mocks/MockSynBook6.sol, contracts/package.json, contracts/synbook/types/SynBook6.sol, package.json, test/unit/synbook/SynBook6.test.ts
Adds unified synthetic orderbook mechanism library.
Allows consumer to compute average spread for orders over a continuous, degree-3 polynomial synthetic representation of an orderbook.
=> Add SynBook6

src/accumulator/types/Accumulator6.sol, src/accumulator/types/UAccumulator6.sol, src/number/types/Fixed18.sol, src/number/types/Fixed6.sol, src/number/types/UFixed18.sol, src/number/types/UFixed6.sol, src/token/types/Token18.sol, src/token/types/Token6.sol, test/accumulator/Accumulator6.t.sol, test/accumulator/UAccumulator6.t.sol, test/number/Fixed18.t.sol, test/number/Fixed6.t.sol, test/number/UFixed18.t.sol, test/number/UFixed6.t.sol, test/token/Token18.t.sol, test/token/Token6.t.sol
Issue: https://linear.app/perennial/issue/PE-2451/[root]-remove-storage-helper-from-type-contracts
=> Remove storage helpers from type contracts

.solhint.json, src/attribute/Factory.sol, src/attribute/Initializable.sol, src/attribute/Instance.sol, src/attribute/Ownable.sol, src/attribute/Pausable.sol
- Update storage pattern of all attributes to use ERC7301.
- Add `_pause()` / `_unpause()` hooks to Pausable for use in inherited contracts.
- Remove `_sender()` hook in `Pausable` and `Ownable` left over from the previous cross-chain support.
=> Misc Updates

src/number/types/Fixed18.sol, src/number/types/Fixed6.sol
Issue: https://linear.app/perennial/issue/PE-1989/root-improve-performance-of-fixed6sign-and-fixed18sign
- Improved gas efficiency of the `sign` method using assembly. Surprisingly, we don't even need to unwrap when using assembly.
Here are different implementations with their gas costs:
- Using only assembly
```
function sign(Fixed6 a) internal pure returns (int256 result) {
assembly {
result := sgt(a, 0)
result := sub(result, slt(a, 0))
}
}
```
```
|----------------------------------------------+-----------------+-----+--------+-----+---------|
| Function Name                                | Min             | Avg | Median | Max | # Calls |
|----------------------------------------------+-----------------+-----+--------+-----+---------|
| sign                                         | …
```
=> Improve gas efficiency of sign method

src/distribution/Treasury.sol, src/token/types/Token.sol, src/token/types/Token18.sol, src/token/types/Token6.sol, test/distribution/Treasury.t.sol, test/token/Token.t.sol, test/token/Token18.t.sol, test/token/Token6.t.sol
Issue: https://linear.app/perennial/issue/PE-2619/root-add-allowance-to-root-tokens
- Added allowance methods to Tokens to get the spender allowance for the caller and the account.
=> Add `allowance` method to tokens

src/mutability/Mutable.sol, src/mutability/interfaces/IMutable.sol, test/mutability/Mutable.t.sol
Resolves: https://github.com/equilibria-xyz/root/pull/142#discussion_r2090228409.
Since the version check happens in the `Mutable` now instead of the `Implementation`, we don't have a way of checking for re-initialization within the `construct()` method directly. This allows construct to be called repeatedly by anyone.
Instead of sharing state between the `Mutable` and `Implementation`, we can simply block `construct()` from being called through our transparent fallback. Since this method must be defined exactly on each implementation, it's will never be needed to be called directly, rather only through the `Mutator` upgrade flow.
=> [Fix] Mutable constructor access

src/distribution/Airdrop.sol, src/distribution/interfaces/IAirdrop.sol, test/distribution/Airdrop.t.sol
Issue: https://linear.app/perennial/issue/PE-2705/root-additional-airdrop-functions
- Update Airdrop contract to use root's Ownable contract.
- Adds `drain` method to withdraw unused tokens from the contract.
- Adds `removeDistribution` method to remove invalid/incorrect merkle root.
=> Additional airdrop feature

src/mutability/Mutator.sol, src/mutability/interfaces/IMutable.sol
Any upgrade which transfers ETH will fail because `construct` is nonpayable.  Update interface making upgrades nonpayable, as we have no use for such functionality.
=> Upgrades should not be payable

src/number/types/UFixed6.sol, test/number/UFixed6.t.sol
Issue: https://linear.app/perennial/issue/PE-2914/root-rename-muldivfixed-to-muldiv
=> Rename `mulDivFixed` to `mulDiv` and `muldivOutFixed` to `muldivOut`
