contracts/mocks/MockUInitializable.sol
contracts/package.json
package.json
test/unit/control/UInitializer.test.ts
yarn.lock

Updates the coverage library and adds one missing test for `UInitializer` versions.

[Fix] Update coverage

---

contracts/mocks/MockFixed18.sol
contracts/mocks/MockUFixed18.sol
contracts/number/types/Fixed18.sol
contracts/number/types/UFixed18.sol
test/unit/number/Fixed18.test.ts
test/unit/number/UFixed18.test.ts

Adds two new `.muldiv()` functions to each fixed-decimal type:

Add muldiv support

---

contracts/control/unstructured/CrossChainOwnable/UCrossChainOwnable.sol
contracts/control/unstructured/CrossChainOwnable/UCrossChainOwnable_Arbitrum.sol
contracts/control/unstructured/CrossChainOwnable/UCrossChainOwnable_Optimism.sol
contracts/control/unstructured/UOwnable.sol
contracts/mocks/MockUCrossChainOwnable_Arbitrum.sol
contracts/mocks/MockUCrossChainOwnable_Optimism.sol
contracts/mocks/MockUOwnable.sol
hardhat.config.ts
package.json
test/unit/control/UCrossChainOwnable_Arbitrum.test.ts
test/unit/control/UCrossChainOwnable_Optimism.test.ts
test/unit/control/UOwnable.test.ts
yarn.lock

Add UCrossChainOwnable

---

contracts/control/unstructured/CrossChainOwner/UCrossChainOwner.sol
contracts/control/unstructured/CrossChainOwner/UCrossChainOwner_Arbitrum.sol
contracts/control/unstructured/CrossChainOwner/UCrossChainOwner_Optimism.sol
contracts/control/unstructured/UOwnable.sol
contracts/mocks/MockERC20.sol
hardhat.config.ts
test/unit/control/UCrossChainOwner_Arbitrum.test.ts
test/unit/control/UCrossChainOwner_Optimism.test.ts

Adds a deployable `UCrossChainOwner` contract for both Optimism and Arbitrum

UCrossChainOwner

---

contracts/mocks/MockFixed18.sol
contracts/mocks/MockFixed6.sol
contracts/mocks/MockToken6.sol
contracts/mocks/MockUFixed18.sol
contracts/mocks/MockUFixed6.sol
contracts/number/types/Fixed18.sol
contracts/number/types/Fixed6.sol
contracts/number/types/UFixed18.sol
contracts/number/types/UFixed6.sol
contracts/token/types/Token6.sol
test/testutil/index.ts
test/testutil/number.ts
test/unit/number/Fixed18.test.ts
test/unit/number/Fixed6.test.ts
test/unit/number/UFixed18.test.ts
test/unit/number/UFixed6.test.ts
test/unit/token/Token6.test.ts

For (U)Fixed6, I:
1. Copy/pasted from base 18
2. Replaced "18" with "6"
3. Changed the base to 1e6
4. Removed pack methods

UFixed6, Fixed6, Token6

---

test/unit/accumulator/UAccumulator6.test.ts

Remove .only

---

contracts/control/interfaces/IOwnable.sol
contracts/control/interfaces/IReentrancyGuard.sol

Adds missing `IInitializable` interface to:
- `IOwnable`
- `IReentrancyGuard`

Add IInitializable to interfaces

---

contracts/attribute/CrossChainOwnable/CrossChainOwnable.sol
contracts/attribute/CrossChainOwner/CrossChainOwner.sol
contracts/attribute/Factory.sol
contracts/attribute/Initializable.sol
contracts/attribute/Kept/Kept.sol
contracts/attribute/Ownable.sol
contracts/attribute/Pausable.sol
contracts/attribute/ReentrancyGuard.sol
contracts/attribute/interfaces/IInitializable.sol
contracts/attribute/interfaces/IOwnable.sol
contracts/attribute/interfaces/IPausable.sol
contracts/attribute/interfaces/IReentrancyGuard.sol
contracts/mocks/MockCrossChainOwnable_Arbitrum.sol
contracts/mocks/MockCrossChainOwnable_Optimism.sol
contracts/mocks/MockInitializable.sol
contracts/mocks/MockKept.sol
contracts/mocks/MockKept_Arbitrum.sol
contracts/mocks/MockKept_Optimism.sol
contracts/mocks/MockOwnable.sol
contracts/mocks/MockPausable.sol
contracts/mocks/MockReentrancyGuard.sol
test/unit/attribute/CrossChainOwnable_Arbitrum.test.ts
test/unit/attribute/CrossChainOwnable_Optimism.test.ts
test/unit/attribute/CrossChainOwner_Arbitrum.test.ts
test/unit/attribute/CrossChainOwner_Optimism.test.ts
test/unit/attribute/Initializable.test.ts
test/unit/attribute/Pausable.test.ts

Fixes leftover unstructured naming

[Cleanup] Fix Naming

---

contracts/adiabatic/AdiabaticMath6.sol
contracts/adiabatic/types/InverseAdiabatic6.sol
contracts/adiabatic/types/LinearAdiabatic6.sol
contracts/mocks/MockAdiabaticMath6.sol
contracts/mocks/MockInverseAdiabatic6.sol
contracts/mocks/MockLinearAdiabatic6.sol
contracts/package.json
test/unit/adiabatic/AdiabaticMath6.test.ts
test/unit/adiabatic/InverseAdiabatic6.test.ts
test/unit/adiabatic/LinearAdiabatic6.test.ts

Adds `LinearAdiabatic6` / `InverseAdiabatic6`

Adiabatic fee types

---

contracts/attribute/Kept/Kept_Optimism.sol
test/unit/attribute/Kept_Arbitrum.test.ts
test/unit/attribute/Kept_Optimism.test.ts

https://github.com/sherlock-audit/2024-02-perennial-v2-3-judging/issues/10

[v2.2 Audit Fix] Optimism_Kept calldata fee calculation

---

contracts/verifier/interfaces/IVerifierBase.sol

Corrected an error signature which caused some head scratching.  And fixed a whitespace issue.

Corrected error signature

---

.solcover.js
contracts/mocks/MockFactory.sol
contracts/mocks/MockInstance.sol
contracts/mocks/MockJumpRateUtilizationCurve18.sol
contracts/mocks/MockJumpRateUtilizationCurve6.sol
contracts/mocks/MockKept.sol
contracts/mocks/MockOwnable.sol
contracts/mocks/MockPausable.sol
contracts/mocks/MockReentrancyGuard.sol
contracts/mocks/MockUJumpRateUtilizationCurve18.sol
contracts/mocks/MockUJumpRateUtilizationCurve6.sol
test/unit/attribute/CrossChainOwnable_Arbitrum.test.ts
test/unit/attribute/CrossChainOwner_Optimism.test.ts
test/unit/attribute/Factory.test.ts
test/unit/attribute/Instance.test.ts
test/unit/attribute/Kept.test.ts
test/unit/attribute/Ownable.test.ts
test/unit/attribute/Pausable.test.ts
test/unit/attribute/ReentrancyGuard.test.ts
test/unit/gas/GasOracle_Arbitrum.test.ts
test/unit/gas/GasOracle_Optimism.test.ts
test/unit/pid/PController6.test.ts
test/unit/utilization/JumpRateUtilizationCurve18.test.ts
test/unit/utilization/JumpRateUtilizationCurve6.test.ts
test/unit/utilization/UJumpRateUtilizationCurve18.test.ts
test/unit/utilization/UJumpRateUtilizationCurve6.test.ts

100% coverage except: 
- Mock files
- [49](https://github.com/equilibria-xyz/root/blob/9a74b55dbe6a3150c320b066d22a4b94b05b68b1/contracts/pid/types/PController6.sol#L49) branch. This is not getting covered although I have updated this [test](https://github.com/equilibria-xyz/root/blob/prateek/pe-616-root-coverage/test/unit/pid/PController6.test.ts#L236) to cover for the missing if branch

Increase root coverage

---

contracts/mocks/MockFixed18.sol
contracts/mocks/MockFixed6.sol
contracts/mocks/MockUFixed18.sol
contracts/mocks/MockUFixed6.sol
contracts/number/types/Fixed18.sol
contracts/number/types/Fixed6.sol
contracts/number/types/UFixed18.sol
contracts/number/types/UFixed6.sol
test/unit/number/Fixed18.test.ts
test/unit/number/Fixed6.test.ts
test/unit/number/UFixed18.test.ts
test/unit/number/UFixed6.test.ts

Issue: https://linear.app/perennial/issue/PE-1154/[root]-make-fixedfromsignificand-exponent-helper

add `fromSignificandAndExponent` for Fixed6 and Fixed18

---

.github/workflows/CI.yml
contracts/access/ProxyOwner.sol
contracts/adiabatic/AdiabaticMath6.sol
contracts/attribute/interfaces/IFactory.sol
contracts/attribute/interfaces/IInitializable.sol
contracts/attribute/interfaces/IInstance.sol
contracts/attribute/interfaces/IOwnable.sol
contracts/attribute/interfaces/IPausable.sol
contracts/attribute/interfaces/IReentrancyGuard.sol
contracts/number/NumberMath.sol
contracts/number/types/Fixed18.sol
contracts/number/types/Fixed6.sol
contracts/number/types/UFixed18.sol
contracts/number/types/UFixed6.sol
contracts/token/types/TokenOrEther18.sol
contracts/utilization/CurveMath18.sol
contracts/utilization/CurveMath6.sol

https://linear.app/perennial/issue/PE-1997/[devex]-add-error-sigs-to-root

Error signatures

---

.github/workflows/CI.yml
contracts/mocks/MockFixed18.sol
contracts/mocks/MockFixed6.sol
contracts/mocks/MockUFixed18.sol
contracts/mocks/MockUFixed6.sol
contracts/number/types/Fixed18.sol
contracts/number/types/Fixed6.sol
contracts/number/types/UFixed18.sol
contracts/number/types/UFixed6.sol
test/unit/number/Fixed18.test.ts
test/unit/number/Fixed6.test.ts
test/unit/number/UFixed18.test.ts
test/unit/number/UFixed6.test.ts

Issue: https://linear.app/perennial/issue/PE-2013/[root]-add-inside-outside-to-fixed-number-type

Add in range methods

---

.github/scripts/comment.js
.github/workflows/CI.yml
Makefile
README.md
slither.config.json

Slither is a static analysis tool.  It will not address style concerns and does not have a rule forbidding console statements.  This PR configures it for our project, omits libraries, and skips two detectors on basis of "we're doing that intentionally and for good reason".  Includes CI task which creates markdown report as PR comment.
Out of scope: Will explore linters (maybe use `solhint` as before) in another PR.

Slither static analysis

---

src/access/ProxyOwner.sol
src/accumulator/types/Accumulator6.sol
src/accumulator/types/UAccumulator6.sol
src/attribute/Initializable.sol
src/attribute/Ownable.sol
src/attribute/OwnableStub.sol
src/attribute/OwnerDelegatable.sol
src/attribute/OwnerExecutable.sol
src/attribute/OwnerWithdrawable.sol
src/attribute/Pausable.sol
src/number/NumberMath.sol
src/number/types/Fixed18.sol
src/number/types/Fixed6.sol
src/number/types/UFixed18.sol
src/number/types/UFixed6.sol
src/synbook/types/SynBook6.sol
src/token/types/Token18.sol
src/token/types/Token6.sol
src/utilization/CurveMath18.sol
src/utilization/CurveMath6.sol
src/utilization/types/JumpRateUtilizationCurve18.sol
src/utilization/types/JumpRateUtilizationCurve6.sol
src/utils/console.sol
test/utils/console.t.sol

Issue: https://linear.app/perennial/issue/PE-2457/[root]-update-all-natspec-from-to-format

Update natspec format

---

src/mutability/interfaces/IAttribute.sol
src/mutability/interfaces/IMutable.sol

Issue: https://linear.app/perennial/issue/PE-2037/root-document-error-hashes-in-root-library-interfaces

Add error natspec

---

Makefile
src/utils/OwnableStub.sol
test/attribute/OwnableStub.t.sol
test/utils/OwnableStub.t.sol

https://linear.app/perennial/issue/PE-2548/root-add-derived-folder
Also exclude new deploy script from coverage.

move OwnableStub

---

src/attribute/Delegatable.sol
src/attribute/Executable.sol
src/attribute/Withdrawable.sol
src/attribute/interfaces/IDelegatable.sol
src/attribute/interfaces/IExecutable.sol
src/attribute/interfaces/IWithdrawable.sol
src/utils/OwnableStub.sol
test/attribute/Delegatable.t.sol
test/attribute/Executable.t.sol
test/attribute/Withdrawable.t.sol
test/distribution/Treasury.t.sol
test/utils/OwnableStub.t.sol

Also moves OwnableStub to `utils`.

Update OwnerXXX Attributes
